# -*- coding: utf-8 -*-
"""Copia de ta21_week13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYGmEBtNeZ5dSgFjAfVlDOrXDWeuUKq_

#**TRABAJO AUTONOMO 21**

El DataFrame df contiene información sobre los consumos nutricionales de pacientes.

Cada fila representa el consumo mensual con las siguientes columnas:

| Columna       | Descripción                                                 |
| ------------- | ----------------------------------------------------------- |
| **Paciente**  | ID del paciente                                             |
| **Sexo**      | F o M (corresponde a femenino o masculino)                  |
| **Edad**      | Edad en años                                                |
| **Mes**       | Valor del 1 al 12                                           |
| **Tipo**      | Tipo de alimento (Frutas, Verduras, Carnes, Cereales, etc.) |
| **Calorías**  | Kilocalorías consumidas                                     |
| **Proteínas** | Kilogramos de proteínas consumidas                          |

Nota: La tabla adjunta muestra información de ejemplo.

| Paciente | Sexo | Edad | Mes | Tipo     | Calorías | Proteínas |
| -------- | ---- | ---- | --- | -------- | -------- | --------- |
| P001     | F    | 35   | 1   | Frutas   | 5000     | 63        |
| P001     | F    | 35   | 2   | Verduras | 4800     | 60        |
| P001     | F    | 35   | 3   | Cereales | 30000    | 750       |
| P002     | M    | 42   | 1   | Frutas   | 5200     | 65        |
| ...      | ...  | ...  | ... | ...      | ...      | ...       |
| P012     | M    | 29   | 1   | Carnes   | 2000     | 480       |
| P012     | M    | 29   | 7   | Frutas   | 6200     | 74        |
| P003     | F    | 51   | 5   | Cereales | 22000    | 831       |
| P005     | F    | 60   | 1   | Frutas   | 5800     | 73        |

**ACTIVIDAD 1**

Agregue una columna llamada Edad_str que clasifique a los pacientes en:

'Joven' → si la edad es menor que 35

'Adulto' → si la edad está entre 35 y 59 inclusive

'Senior' → si la edad es mayor o igual que 60

Respuesta esperada:
Código para agregar la nueva columna de tipo str.
"""

#Utilice la siguiente propuesta de dataframe para trabajar su programa
import pandas as pd
import numpy as np

# Semilla para reproducibilidad
np.random.seed()

# Datos base
pacientes = [f"P{str(i).zfill(3)}" for i in range(1, 16)]  # 15 pacientes (P001–P015)
sexos = ["F", "M"]
tipos = ["Frutas", "Verduras", "Cereales", "Carnes", "Lácteos"]

# Generar 100 registros aleatorios
df = pd.DataFrame({
    "Paciente": np.random.choice(pacientes, 100),
    "Sexo": np.random.choice(sexos, 100),
    "Edad": np.random.randint(20, 80, 100),
    "Mes": np.random.randint(1, 13, 100),
    "Tipo": np.random.choice(tipos, 100),
    "Calorías": np.random.randint(1500, 30000, 100),
    "Proteínas": np.random.randint(40, 900, 100)
})

print(df.head(25))

#SOLUCION ACTIVIDAD 01
def clasificar_grupo(edad):
    if edad < 35:
        return 'Joven'
    elif 35 <= edad <= 59:
        return 'Adulto'
    else:
        return 'Senior'

df['Edad_str'] = df['Edad'].apply(clasificar_grupo)

print(df)

"""**ACTIVIDAD 2**

Seleccione a los pacientes más longevos (‘Senior’) y calcule el promedio de las Calorías consumidas por ese grupo.

*Respuesta esperada:* Un número (float) que representa el promedio, guardado en la variable **promedio**.
"""

#SOLUCION ACTIVIDAD 2
filtro_senior = df['Edad_str'] == 'Senior'
df_seniors = df[filtro_senior]

promedio = df_seniors['Calorías'].mean()

print(f"El promedio de calorías de los Seniors es: {promedio:.2f}")

"""**ACTIVIDAD 3**

¿Cuál es el tipo de alimento cuyo promedio de Calorías es el más alto en el DataFrame?

Respuesta esperada: Una cadena de texto (str) con el valor del tipo de alimento, guardada en la variable resultado.
"""

# SOLUCION ACTIVIDAD 3
promedios = df.groupby('Tipo')['Calorías'].mean()

resultado = promedios.idxmax() # Queremos la etiqueta del máximo, más no el valor máximo (no .max())

print(f"El alimento con más calorías es: {resultado}")

"""**ACTIVIDAD 4**

Considerando únicamente los registros del primer trimestre (meses 1 a 3) y el tipo de alimento "Cereales", calcule la cantidad total de registros correspondientes al sexo femenino.

Respuesta esperada: Un número entero (int) almacenado en la variable total.
"""

# SOLUCION ACTIVIDAD 4
condicion_tiempo = df['Mes'] <= 3
condicion_tipo   = df['Tipo'] == 'Cereales'
condicion_sexo   = df['Sexo'] == 'F'

df_filtrado = df[condicion_tiempo & condicion_tipo & condicion_sexo]

total = len(df_filtrado)

print(f"El total de registros encontrados es: {total}")

"""**ACTIVIDAD 5**

Cree una variable pacientes a partir del DataFrame df que contenga:

Paciente: El ID del paciente

Calorías: El total de calorías consumidas por paciente

Considere que cada paciente tiene varios registros en el DataFrame original.

Finalmente, ordene los datos de pacientes por el consumo total de calorías (de mayor a menor) y guarde estos datos en un archivo CSV llamado calorias_paciente.csv
"""

# SOLUCION ACTIVIDAD 5
pacientes = df.groupby('Paciente')['Calorías'].sum().reset_index()

pacientes = pacientes.sort_values('Calorías', ascending=False)

pacientes.to_csv('calorias_paciente.csv', index=False)