# -*- coding: utf-8 -*-
"""Copia de Taller week8taller.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFQnlk2BP9JXFeBzGb4hxYFXFS6ir3eS

**DICCIONARIOS**


* Se define mediante un par de elementos: CLAVE y el VALOR asociado a una clave.
* Las clave pueden ser del tipo: int, str o bool y son únicas.
* Los valores pueden ser de cualquier tipo y se asocian a una clave.
"""

#DICCIONARIOS
dict_notas = {"Ana": 8, "Pedro": 7.5, "Juan": 5.7} #Coleccion de datos heterogenea
print(dict_notas)

#Mutabilidad del Diccionario
dict_notas["Ana"] = 7 # Se modifica por medio de la clave
print(dict_notas)

#Agregar un elemento (clave,valor) al diccionario
dict_notas["Diego"] = 9.5
print(dict_notas)

dict_notas["Juan Ignacio"] = 3.3
print(dict_notas)

#Eliminar un elemento del diccionario
retirado_est = dict_notas.pop("Juan Ignacio")
print(dict_notas)
print(f"La nota del estudiante que se retiró es: {retirado_est}")

#Acceder a un elemento del diccionario
notaDiego = dict_notas["diego"]
print(notaDiego)

#Acceder por medio de get()
notaDiego = dict_notas.get("diego","Nombre no encontrado")
print(notaDiego)

# Agregar elementos nuevos sin modificar los anteriores
est5 = dict_notas.setdefault("Sebastian",8.4)
print(f"Calficacion de Sebastian: {est5}")
print(dict_notas)
est6 = dict_notas.setdefault("Juan",9)
print(f"Calficacion de Juan: {est6}")
print(dict_notas)

"""**FUNCIONES CON DICCIONARIOS**
*   Conocer el tamaño del diccionario
*   Saber si existe un elemento (Busqueda)
*   Determinar el valor Min o Max de un diccionario
*   Ordenar los elementos de un diccionario
*   Convertir un diccionario en una lista





"""

#Tamaño de un diccionario
cant_est = len(dict_notas)
print(f"El tamaño del diccionario notas es: {cant_est}")

#Funcion de Busqueda
est_busq = "Sebastian"
if est_busq in dict_notas:
  print(f"La nota de {est_busq} es: {dict_notas[est_busq]}")
else:
  print(f"No existe el mencionado estudiante en el registro de notas")

#Min y Max
print(f"El primer estudiante en el registro de notas es: {min(dict_notas)}")
print(f"El ultimo estudiante en el registro de notas es: {max(dict_notas)}")

#Ordenar un diccionario
notas_ordenadas = sorted(dict_notas) #Obtener una lista con las claves(estudiante) ordenadas de manera alfabetica
print(f"{notas_ordenadas}")
print(dict_notas)

for estudiante in notas_ordenadas:
  print(f"{estudiante}: {dict_notas[estudiante]} ")

#Convertir un diccionario en lista
l_notas = list(dict_notas) #Una lista de las claves(estudiantes) del diccionario en su orden original
print(l_notas)

"""**ITERAR O RECORRER UN DICCIONARIO**"""

#Primer lazo for
for iteradora in dict_notas:
  print(iteradora)
print()
#Segundo lazo for
for iteradora in dict_notas.keys():
    print(iteradora)
print()
#Tercer lazo for
for iteradora in dict_notas.values():
  print(iteradora)
print()
#Cuarto lazo for
for iteradora in dict_notas.items():
  print(f"{list(iteradora)}")
print()
for iteradora1, iteradora2 in dict_notas.items():
  print(iteradora1)
  print(iteradora2)

"""\## Taller: Agrupación de palabras por longitud

Dada una lista de palabras, escribe una función que cree un diccionario donde:

* Claves: las longitudes de las palabras.
* Valores: listas con las palabras que tengan esa longitud.
|
**Entrada:**
```python
palabras = ['hola', 'mundo', 'python', 'es', 'genial', 'aprender']
```
**Salida:**
```python
{4: ['hola'], 5: ['mundo'], 6: ['python', 'genial'], 2: ['es'], 8: ['aprender']}
```
Restricciones:

* Puedes asumir que todas las palabras son cadenas de texto válidas.
* Muestre en pantalla el diccionario.

**Pista:**

* Usa diccionario para agrupar las palabras por longitud.

"""

def crear_diccionario(palabras):
  diccionario = {}
  for palabra in palabras:
    lista_temporal = []
    lista_temporal.append(palabra)

    if len(palabra) in diccionario:
      lista_repetidos = []
      lista_repetidos.append(diccionario[len(palabra)][0])
      lista_repetidos.append(palabra)
      diccionario[len(palabra)] = lista_repetidos

    else:
      diccionario[len(palabra)] = lista_temporal

  return diccionario

print(crear_diccionario(['hola', 'mundo', 'python', 'es', 'genial', 'aprender']))

