# -*- coding: utf-8 -*-
"""Copia de Semana11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlTGAmDEFfKu7-uY5BvMdbQDZPHrIoPR

ARREGLOS NUMPY
"""

# LIBRERIAS
import numpy as np
import time
import random
# FUNCIONEs

# PRINCIPAL

# Tamaño de los datos
N = 10000000

# Crear una lista y un arreglo con números aleatorios
lista = []
for i in range(N):
    lista.append(random.random())

arreglo = np.random.rand(N)

# Operación: suma de elementos
inicio_lista = time.time()
suma_lista = sum(lista)
tiempo_lista = time.time() - inicio_lista

inicio_arreglo = time.time()
suma_arreglo = np.sum(arreglo)
tiempo_arreglo = time.time() - inicio_arreglo

print("Suma con lista: %.6f, Tiempo: %.6f segundos" %(suma_lista,tiempo_lista))
print("Suma con arreglo: %.6f, Tiempo: %.6f segundos" %(suma_arreglo,tiempo_arreglo))

# Operación: multiplicación de elementos por 2
inicio_lista = time.time()
lista_por_2 = []
for i in lista:
    lista_por_2 = i * 2
tiempo_lista = time.time() - inicio_lista

inicio_arreglo = time.time()
arreglo_por_2 = arreglo * 2
tiempo_arreglo = time.time() - inicio_arreglo

print("Multiplicación lista Tiempo: %.6f segundos" % tiempo_lista)
print("Multiplicación arreglo Tiempo:%.6f segundos" % tiempo_arreglo)

"""### Ejercicio 01: Manipulación de temperaturas

Se tiene un arreglo NumPy llamado arr_temperaturas que contiene las temperaturas registradas en una ciudad durante una semana. (Genere 7 temperaturas de manera aleatoria entre 22 y 38 en formato int). Defina una Lista con los siete días de la semana llamado lista_semana.
A continuación, implemente lo siguiente:
1.	Imprima la temperatura del cuarto día de la semana. (Utilice como formato de presentación la lista y el arreglo)
2.	Imprima las temperaturas de los primeros tres días de la semana. (Utilice como formato de presentación la lista y el arreglo)
3.	Calcule e imprima el promedio de las temperaturas de los días pares de la semana.
4.	Imprima los días de la semana en los que la temperatura fue superior a 28 grados. (Utilice como formato de presentación la lista y el arreglo)
Nota: Asuma que los días de la semana están representados por los índices del arreglo, donde 0 es lunes, 1 es martes y así sucesivamente.



"""

import numpy as np

arr_temperaturas = np.random.randint(22, 39, size=7)

lista_semana = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

print("Datos:")
print("Días:", lista_semana)
print("Temperaturas:", arr_temperaturas)

print("\n1. Temperatura del cuarto día:")
print(f"{lista_semana[3]}: {arr_temperaturas[3]} grados")

print("\n2. Temperaturas de los primeros tres días:")
for i in range(3):
    print(f"{lista_semana[i]}: {arr_temperaturas[i]} grados")


print("\n3. Promedio de temperaturas en días pares:")
temps_pares = arr_temperaturas[::2]
promedio = np.mean(temps_pares)

print(f"Temperaturas tomadas: {temps_pares}")
print(f"Promedio: {promedio:.2f}")

print("\n4. Días con temperatura mayor a 28 grados:")

condicion = arr_temperaturas > 28

dias_filtrados = np.array(lista_semana)[condicion]
temps_filtradas = arr_temperaturas[condicion]

cantidad_dias = len(dias_filtrados)

for i in range(cantidad_dias):
    print(f"{dias_filtrados[i]}: {temps_filtradas[i]} grados")