# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_F5xBX_6zDLSakgmqUnMso53631KBRx7

Tema 1. Operaciones y Funciones con cadena  (30 p)
1.1 Se tiene una cadena de caracteres con la siguiente estructura:
```python
frase = "nombre: juan perez, ciudad: guayaquil, profesion: ingeniero"
```
i.	Extrae las palabras correspondientes al nombre, ciudad y profesión.

ii.	Muestra los resultados con etiquetas en mayúsculas y los valores en formato título (inicial en mayúscula).

iii.	Alinea cada etiqueta a la izquierda con 12 caracteres de espacio.
Ejemplo de salida esperada:
```python
NOMBRE      : Juan Perez
CIUDAD      : Guayaquil
PROFESION   : Ingeniero
```
"""

# Ejercicio 1
frase = "nombre: juan perez, ciudad: guayaquil, profesion: ingeniero"
# Literal 1
name,city,profesion = frase.split(", ")
name01,nome_value = name.split(": ")
city01,city_value = city. split(": ")
profesion01,profesion_value = profesion.split(": ")

# Literal 2 y 3
print (f"{name01.upper():<12}: {nome_value.title()}")
print (f"{city01.upper():<12}: {city_value.title()}")
print (f"{profesion01.upper():<12}: {profesion_value.title()}")

"""1.2 Dada una lista con una frase dividida en palabras, concatena las palabras en una nueva frase. Luego, reemplaza la palabra "es" por "ES" y muestra la frase resultante con formato título.

Ejemplo de salida:
```python
palabras = ["python", "es", "divertido", "de", "usar"]
Python ES Divertido De Usar
```


"""

# Ejercicio 2
palabras = ["python", "es", "divertido", "de", "usar", "es", "como", "lo", "esperaba"]

cadena_palabras = " ".join(palabras)
cadena_palabras = cadena_palabras.title()
cadena_palabras = cadena_palabras.replace("Es", "ES")

print(cadena_palabras)
print("-".join(cadena_palabras)) # Ejemplo de join

"""Tema 2. Listas, Cadenas de Caracteres y Aleatoriedad (40 p)
Una empresa ha recolectado comentarios de sus usuarios en una lista. Cada comentario es una cadena de texto. Se desea procesar estos comentarios para fines de análisis. Se te solicita lo siguiente:

i.	Seleccionar al azar un comentario y mostrarlo.

ii.	Reemplazar todas las ocurrencias de una palabra sensible (ej. "malo") por "***" en el comentario seleccionado.

iii.	Contar cuántas veces aparece la palabra "servicio" en el comentario original antes del reemplazo.

iv.	Convertir el comentario a minúsculas y mostrarlo.

v.	Unir todos los comentarios originales en una sola cadena, separadas por punto y espacio.

vi.	Mostrar los últimos 25 caracteres de la cadena concatenada.
Ejemplo de salida:
```python
Lista de comentarios:
['El servicio fue bueno.', 'Muy mala experiencia.', 'Excelente atención.', 'El servicio al cliente debe mejorar.', 'Demasiado lento y malo.']

Comentario aleatorio seleccionado:
Demasiado lento y malo.

Comentario con palabra censurada:
Demasiado lento y ***.

La palabra 'servicio' aparece: 0 veces

Comentario en minúsculas:
demasiado lento y malo.

Comentarios unidos:
El servicio fue bueno. Muy mala experiencia. Excelente atención. El servicio al cliente debe mejorar. Demasiado lento y malo.

Ultimos 25 caracteres de la cadena final:
. Demasiado lento y malo.
```

"""

import random as rd

lista_de_comentarios = ["El servicio fue bueno.", "Muy mala experiencia.", "Excelente atención.",
                        "El servicio al cliente debe mejorar.", "Demasiado lento y malo.", "El servicio fue MALo"]
palabra_sensible = "malo"

# Literal 1
comentario_aleatorio = rd.choice(lista_de_comentarios)
print(f'Comentario aleatorio seleccionado:\n{comentario_aleatorio}')

# Literal 2
comentario_sensible = comentario_aleatorio.lower().replace(palabra_sensible, "***")
print(f'\nComentario con palabra censurada: \n{comentario_sensible}')

# Literal 3
cantidad = comentario_aleatorio.lower().count("servicio")
print(f'\nLa palabra \'servicio\' aparece {cantidad} veces')

# Literal 4
print(f'\nComentario en minúsculas:\n{comentario_aleatorio.lower()}')

# Literal 5
cadena_comentarios = " ".join(lista_de_comentarios)
print(f'\nComentarios unidos:\n{cadena_comentarios}')

# Literal 6
ultimos25 = cadena_comentarios[-25:]
print(f'\nÚltimos 25 caracteres de la cadena final:\n{ultimos25}')