# -*- coding: utf-8 -*-
"""mi_primer_programa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UeY-xeS-gjrE0dLtsS_-z8MaQTw2vRlm

# Mi primer programa
### En este ejercicio, tu objetivo es imprimir `tu nombre, tu edad, tu matrícula y tu carrera` en pantalla utilizando la función `print()` en Python.

Para hacerlo realiza los siguientes pasos:

1. Copia y pega el siguiente código en la celda para codificar. Recuerda reemplazar tu nombre donde dice `[tu nombre aquí]`.
```python
print("Hola, mi nombre es [tu nombre aquí]!")
```
2. Ejecuta tu código dando clic en el botón "Run cell" que se muestra a la izquierda de tu código. También se puede ejecutar el código con el atajo de teclas (Ctrl + Enter).

3. Crea una variable para almacenar tu edad. Colócala como segunda línea, es decir, después del print. Ejemplo:
```python
print("Hola, mi nombre es Juan Perez!")
mi_edad = 18
```

4. A continuación, copia y pega el siguiente código para mostrar tu edad en el programa.
```python
print("Tengo", edad, "años.")
```
5. Ejecuta tu código.

6. Ahora, crea una variable para tu matrícula y almacénala como número entero.

7. También, crea una variable para tu carrera y almacénala como cadena de caracteres.

8. Utilizando `print()` muestra tu matrícula y tu carrera en tu programa. Recuerda separar los datos o variables con comas dentro de los paréntesis de la función `print()`.

9. Finalmente, copia todo el código de tu programa en la actividad correspondiente en el Aula Virtual. También debes subir una captura de la ejecución de tu programa.
"""

print("Hola, mi nombre es Diego!")
mi_edad = 18
print("Tengo", mi_edad, "años.")
mi_matricula = 202516357
mi_carrera = "Ciencia de datos e Inteligencia Artificial"
print("Mi matrícula es:", mi_matricula, "y mi carrera es:", mi_carrera)