# -*- coding: utf-8 -*-
"""Actividad 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16B-AbJgijDjtrcrGG_ATNMMF4-By27YG

**Manejo de archivos (Siempre y cuando sean archivos .csv)**
- Lectura de un archivo: read_csv("ruta", sep, header, index_col)
- Escritura de un archivo: to_csv("nombre_archivo", sep, index)
"""

# Importamos la libreria PANDAS
import pandas as pd
df_paises = pd.read_csv("/paises.csv", sep=",", index_col=3)
print(df_paises)
# el separador por defecto es la coma

# Información del país Colombia
print(df_paises.loc["Colombia"])

# Agregar Columna de Equipos de futbol
df_paises["EquipoFutbol"] = ["BocaJunior", "OnceCaldas", "RealMadrid", "America", "Tachira", "Flamengo", "ColoColo"]
print(df_paises)

# Index df
df_paises_reset = df_paises.reset_index()
print(df_paises_reset)

# Exportar, Guardar, Escribir un Dataframe
df_paises_reset.to_csv("PaisesFP", sep=";", index=False)

# Búsqueda de valores NaN
print(df_paises.isna())

# Contar cuántos NaN tiene la tabla
print(df_paises.isna().sum())

# Reemplazar valores NaN de la columna Categoria
df_paises["Categoria"] = df_paises["Categoria"].fillna("S/N")
print(df_paises)

# Reemplazar los valores NaN de la columna Habit_x_km2 por cero
df_paises["Habit_x_km2"] = df_paises["Habit_x_km2"].fillna(df_paises["Habit_x_km2"].mean())
print(df_paises)