# -*- coding: utf-8 -*-
"""facturaRestaurante.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197FfKgcqKTckcwPQOYRsZUxVGZUqbFzo

Instrucciones:
1. Cada integrante debe iniciar sesión en colab con un usuario de google.
2. El grupo debe elegir un líder que es quién va a realizar la codificación.
3. El líder debe crear una copia de este Notebook de Colab.
4. El líder debe agregar al resto de integrantes para que puedan editar el mismo Notebook.
5. Antes de finalizar el tiempo, debe descargar (**en .py**) el código realizado por su grupo en este Colab. Además, debe capturar la pantalla mostrando el código y el resultado obtenido por su código
6. Enviar al Aula Virtual tanto el **archivo de python** como la **captura de pantalla**.

# Actividad 01: Grupal  
## Repartir la cuenta del restaurante entre amigos.

1. **Guarde la cantidad de amigos:** Crea 1 variable para colocar cuantos amigos están en el restaurante.

2. **Solicitar información inicial:** Crea una variable con el costo total de la cuenta sin impuestos.
   
3. **Calcular el costo del servicio:** Calcula el 10% del costo total. Este valor representa el costo adicional por el servicio del restaurante.
   
4. **Calcular el costo del IVA:** Calcula el 15% del costo total sin impuestos. Este valor representa el impuesto al valor agregado que se debe pagar sobre la cuenta del restaurante.
   
5. **Sumar costos adicionales:** Suma el costo del servicio y el costo del IVA al costo total inicial. Esto nos dará el costo total final que se debe repartir entre los amigos.
   
6. **Dividir el costo total entre amigos:** Divide el costo total final entre 3 amigos para calcular cuánto debe pagar cada uno.
   
7. **Redondear valores:** Al calcular cada costo se puede redondear con 2 decimales para evitar demasiados dígitos de precisión. Use la función `round(valor, nro_decimales)`. Ejemplo:
```python
monto = round(3.45782, 2)
```

8. **Mostrar resultados:** Muestra por pantalla todos los cálculos realizados, incluyendo el costo del servicio, el costo del IVA, el costo total final y el monto que cada amigo debe pagar.
"""

# Primero la cantidad de amigos
cantidad_amigos = 3

# Cuanto deben pagar sin impuestos
costo_total = 100

# Cuanto deben pagar con impuestos
costo_servicio = costo_total * 0.1
iva = costo_total * 0.15
costo_total_final = costo_total + costo_servicio + iva

# Repartir equitativamente el pago
pago_por_amigo = costo_total_final / cantidad_amigos

# Mostrando datos
print("Son ", cantidad_amigos, " personas que van a pagar la cuenta.")
print("El valor a pagar es:")
print("")
print("Costo total (", costo_total, ")")
print("Costo del servicio (", costo_servicio, ")")
print("IVA (", iva, ")")
print("Costo total final: ", costo_total_final)
print("")
print("Cada persona debe pagar", round(pago_por_amigo, 2))

