# -*- coding: utf-8 -*-
"""Copia de week08_post12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ger-7YmtXahcekZTm7mEDAC8spHT8N-

# Intrucciones Generales
1. Lea las instrucciones del trabajo autónomo que se encuentran descritas en el archivo de Colab.
2. Una vez finalizado su trabajo, haga una captura de pantalla del código trabajado por usted, donde se pueda observar el resultado obtenido. La imagen de la captura de pantalla debe estar en formato JPG o PNG.
3. Descargue su trabajo de la plataforma Colab en formato .py.
4. Haga la entrega de su archivo .py y la captura de pantalla de la ejecución de su programa.

## MÓDULO DE BECAS

La Escuela Superior Politécnica del Litoral tiene la necesidad de implementar un Módulo de Becas para el Sistema Académico. Este módulo tendrá la funcionalidad de seleccionar a los estudiantes que tengan los mejores promedios generales por carrera para otorgarles una beca.
El módulo registrará los datos informativos del estudiante.

Datos Informativos del Estudiante
* Número de matrícula
* Nombres y apellidos
* Carrera

Además, el módulo registrará por cada estudiante las asignaturas que cursó en el semestre con su respectivo promedio final.

Datos de la Asignatura
*	Nombre de la materia
*	Promedio final de la asignatura obtenido en el semestre.

**Con la finalidad de implementar el Módulo de Becas, a usted se le solicita crear las siguientes funciones:**

1. La función obtenerInfoEstudiantes(), la cual solicita por teclado los datos informativos de 5 estudiantes y las asignaturas que tomó cada estudiante en el semestre con su respectivo promedio final. La función devuelve un diccionario con la siguiente estructura como ejemplo:
```python
{201145678:{"nombres":"Juan","apellidos":"Guerra","carrera":"Computación",
"asignaturas":("cálculo 1", "física 1", "química"),
"calificaciones":(7.3, 8.4, 6.5)},
 201234348:{"nombres":"Pedro","apellidos":"Perez","carrera":"Ciencias de Datos"
 "asignaturas":("estadística", "computación"),
 "calificaciones":(8.5, 7.4)},
 201233021:{"nombres":"Roberto","apellidos":"Lara","carrera":"Automatización"
 "asignaturas":("cálculo 2", "redes 1",),
 "calificaciones":(9.0, 8.9)}
}
```
2. La función calcularPromediosEstudiantes(dicEstudiantes), la cual recibe el diccionario que contiene toda la información de los estudiantes con sus asignaturas y **devuelve** un nuevo **diccionario** con los promedios generales por cada estudiante. Los promedios generales son calculados a través de todos los promedios finales de las materias que cursó el estudiante en el semestre. Un ejemplo del diccionario que devuelve la función es el siguiente:
```python
{201145678: 7.4, 201234348: 7.95, 201233021: 8.95}
```

3. La función obtenerMejoresPromedios(dicPromedios, incial, final), la cual recibe un diccionario con los promedios finales de los estudiantes y un rango de promedios especificados por un valor inicial y final. La función devuelve una **lista** con los números de matrículas de los estudiantes que obtuvieron los mejores promedios finales de acuerdo al rango especificado. Un ejemplo de la función sería:
```python
obtenerMejoresPromedios(dicPromedios, 7.5, 10.0)
[201234348, 201233021]
```
4. Implementar un programa que solicite el ingreso por teclado de toda la información de los estudiantes con sus respectivas asignaturas. Además, deberá solicitar por teclado el rango de promedios que servirá como criterio para la selección de los estudiantes que serán acreedores a la beca. Finalmente el programa presentará los datos informativos de los estudiantes que fueron acreedores a la Beca, mostrando su promedio general obtenido y a qué carrera pertenecen.
"""



def obtenerInfoEstudiantes(numero_estudiantes = 5):
  datos_estudiantes = {}
  for numero_estudiante in range(1, numero_estudiantes + 1):
    matricula_estudiante = input("\nMatrícula del estudiante: ")
    materias = []
    calificaciones = []
    datos_estudiante = {"nombres": input("Nombres del estudiante: "), "apellidos": input("Apellidos del estudiante: "),
                        "carrera": input("Carrera del estudiante: "), "materias": materias, "calificaciones": calificaciones}

    # Guardar cada materia que se esté cursando, además de su calificación
    numero_materias_estaudiante = int(input("Cuántas materias está cursando el estudiante: "))

    for numero_materia in range(1, numero_materias_estaudiante + 1):
      materia = input(f'Ingrese la materia {numero_materia}: ')
      calificacion = float(input(f'Ingrese la calificación de {materia}: '))
      materias.append(materia)
      calificaciones.append(calificacion)


    # Añadir dato al diccionario
    datos_estudiantes[matricula_estudiante] = datos_estudiante

  return datos_estudiantes

def calcularPromediosEstudiantes(datos_estudiantes):
  promedio_estudiantes = {}
  for clave, valor in datos_estudiantes.items():
    promedio = float(f'{sum(datos_estudiantes[clave]['calificaciones']) / len(datos_estudiantes[clave]['calificaciones']):.2f}')

    promedio_estudiantes[clave] = promedio

  return promedio_estudiantes

def obtenerMejoresPromedios(promedio_estudiantes, inicio, final):
  mejores_promedios = {}
  for clave, valor in promedio_estudiantes.items():
    if valor >= inicio and valor <= final:
      mejores_promedios[clave] = valor

  return mejores_promedios

# Programa principal
numero_estudiantes_registro = int(input("¿Cuántos estudiantes desea registrar?: "))
datos_de_estudiantes = obtenerInfoEstudiantes(numero_estudiantes_registro)

promedio_de_estudiantes = calcularPromediosEstudiantes(datos_de_estudiantes)

rango_inicial = float(input("\nIngrese el rango mínimo para considerar buen promedio: "))
rango_final = float(input("Ingrese el rango máximo para considerar buen promedio: "))
mejores_promedios_estudiantes = obtenerMejoresPromedios(promedio_de_estudiantes, rango_inicial, rango_final)

estudiantes_becados = mejores_promedios_estudiantes

print(f"Los estudiantes seleccionados para la beca fueron:")

for clave, valor in estudiantes_becados.items():
  print(f'Matrícula: {clave}, carrera: {datos_de_estudiantes[clave]['carrera']}')

