# -*- coding: utf-8 -*-
"""Copia de taller13_week13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189nU-rW4F2dRdiryF8HtRlQ7Do9L2ZrZ

# **Análisis de Ciudades del Ecuador con Pandas**

**Parte 1: Manejo de archivos (CSV) y nulos**

Intrucciones:

1. Leer el archivo CSV usando pd.read_csv() con el separador ;
2. Mostrar las primeras filas del DataFrame con .head()
3. Verificar si existen valores nulos con .isna()
4. Reemplazar los valores nulos de temperatura con el promedio general usando fillna()
5. Guardar el DataFrame limpio en un nuevo archivo ciudades_limpio.csv
"""

#SOLUCION
import pandas as pd

# Note que el sperador es "," mas no ";"
df = pd.read_csv("/content/ciudades_ecuador.csv", sep=",")

print(df.head())

valores_nulos = df.isna().sum()
print(valores_nulos)

promedio_temp = df['Temperatura Media (°C)'].mean()
print(f"\nPromedio de temperatura calculado: {promedio_temp:.2f} °C")
df['Temperatura Media (°C)'] = df['Temperatura Media (°C)'].fillna(promedio_temp)

df.to_csv('ciudades_limpio.csv', index=False)

"""**Parte 2: Operaciones lógicas y filtros**

Instrucciones:
1. Seleccionar las ciudades con población mayor a 300,000 y altitud menor a 1,000 m
2. Mostrar solo las columnas Ciudad, Poblacion y Altitud (msnm)
3. Aplicar .mask() para reemplazar temperaturas mayores a 30°C con la media
4. Crear un filtro que muestre ciudades con altitud mayor a 2000 o temperatura menor a 18°C
"""

#SOLUCION
import pandas as pd

df = pd.read_csv('ciudades_ecuador.csv')

filtro_ciudades = df[(df['Poblacion'] > 300000) & (df['Altitud (msnm)'] < 1000)]

print(filtro_ciudades[['Ciudad', 'Poblacion', 'Altitud (msnm)']])

media_temp = df['Temperatura Media (°C)'].mean()
df['Temperatura Media (°C)'] = df['Temperatura Media (°C)'].mask(df['Temperatura Media (°C)'] > 30, media_temp)

filtro_final = df[(df['Altitud (msnm)'] > 2000) | (df['Temperatura Media (°C)'] < 18)]
print(filtro_final)

"""**Parte 3: Agregaciones y estadísticas**

Instrucciones:
1. Ordenar el DataFrame por población de forma descendente (sort_values)
2. Mostrar las 3 ciudades más pobladas (nlargest) y las 3 menos pobladas (nsmallest)
3. Calcular el promedio de población para ciudades costeras y no costeras usando .groupby()
4. Contar cuántas ciudades son costeras y cuántas no (value_counts)
5. Crear una nueva columna "Densidad" aplicando una función con .apply()Fórmula: Densidad = Poblacion / Altitud (msnm)
6. Obtener las ciudades con la densidad más alta y más baja usando .agg()
"""

# SOLUCION
import pandas as pd

df = pd.read_csv('ciudades_ecuador.csv')

df_ordenado = df.sort_values(by='Poblacion', ascending=False)

top_3_pobladas = df.nlargest(3, 'Poblacion')
top_3_menos_pobladas = df.nsmallest(3, 'Poblacion')

promedio_pob_zona = df.groupby('Costera')['Poblacion'].mean()

conteo_zonas = df['Costera'].value_counts()

df['Densidad'] = df.apply(lambda fila: fila['Poblacion'] / fila['Altitud (msnm)'], axis=1)

stats_densidad = df.agg({'Densidad': ['max', 'min']})

print(df_ordenado)
print(top_3_pobladas[['Ciudad', 'Poblacion']])
print(top_3_menos_pobladas[['Ciudad', 'Poblacion']])
print(promedio_pob_zona)
print(conteo_zonas)
print(df[['Ciudad', 'Densidad']])
print(stats_densidad)

"""**Parte 4: Guardar Resultados Finales**

1. Guardar el archivo en formato csv con el nombre: "ciudades_ecuador_procesadas.csv". Use como separador ";"
"""

#SOLUCION
df.to_csv('ciudades_ecuador_procesadas.csv', sep=';', index=False)